import {type Models} from "appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts C:\Users\bhatti\Desktop\alkabir_database`.

export enum Role {
  CUSTOMER = "customer",
  PROFESSIONAL = "professional",
  ADMIN = "admin",
}

export enum Status {
  PENDING = "pending",
  CONFIRMED = "confirmed",
  IN_PROGRESS = "in_progress",
  COMPLETED = "completed",
  CANCELLED = "cancelled",
  RESCHEDULED = "rescheduled",
}

export enum CurrentStatus {
  AVAILABLE = "available",
  BUSY = "busy",
  ON_BREAK = "on_break",
  OFF_DUTY = "off_duty",
}

export enum PaymentMethod {
  CREDIT_CARD = "credit_card",
  DEBIT_CARD = "debit_card",
  CASH = "cash",
  BANK_TRANSFER = "bank_transfer",
  DIGITAL_WALLET = "digital_wallet",
}

export enum Status {
  PENDING = "pending",
  PROCESSING = "processing",
  COMPLETED = "completed",
  FAILED = "failed",
  REFUNDED = "refunded",
  PARTIAL_REFUND = "partial_refund",
}

export enum Type {
  BOOKING = "booking",
  PAYMENT = "payment",
  REVIEW = "review",
  SYSTEM = "system",
}

export enum DiscountType {
  PERCENTAGE = "percentage",
  FIXED_AMOUNT = "fixed_amount",
}

export enum Status {
  NEW = "new",
  IN_PROGRESS = "in_progress",
  RESOLVED = "resolved",
  CLOSED = "closed",
}

export type Profiles = Models.Document & {
  email: string;
  full_name: string;
  phone: string | null;
  avatar_url: string | null;
  role: Role;
  is_active: boolean;
  email_verified: boolean;
  phone_verified: boolean;
};

export type Customers = Models.Document & {
  user_id: string;
  preferred_language: string;
  marketing_consent: boolean;
  loyalty_points: number;
  total_bookings: number;
};

export type Addresses = Models.Document & {
  user_id: string;
  label: string | null;
  street_address: string;
  city: string;
  emirate: string;
  area: string | null;
  is_default: boolean;
};

export type ServiceCategories = Models.Document & {
  name: string;
  slug: string;
  description: string | null;
  icon_url: string | null;
  color: string | null;
  image_url: string | null;
  is_active: boolean;
  display_order: number;
};

export type Services = Models.Document & {
  category_id: string;
  name: string;
  slug: string;
  short_description: string | null;
  full_description: string | null;
  base_price: number;
  currency: string;
  duration_minutes: number | null;
  is_active: boolean;
  is_featured: boolean;
  average_rating: number;
  total_reviews: number;
};

export type Bookings = Models.Document & {
  booking_number: string;
  customer_id: string;
  service_id: string;
  professional_id: string | null;
  address_id: string;
  scheduled_datetime: string;
  status: Status;
  total_amount: number;
  currency: string;
};

export type Professionals = Models.Document & {
  user_id: string;
  employee_id: string;
  specialization: string[] | null;
  years_of_experience: number | null;
  bio: string | null;
  languages: string[] | null;
  average_rating: number;
  is_available: boolean;
  current_status: CurrentStatus;
};

export type Payments = Models.Document & {
  booking_id: string;
  customer_id: string;
  amount: number;
  payment_method: PaymentMethod;
  status: Status;
  transaction_id: string | null;
};

export type Reviews = Models.Document & {
  booking_id: string;
  customer_id: string;
  service_id: string;
  professional_id: string;
  rating: number;
  title: string | null;
  comment: string | null;
  is_published: boolean;
  review_text: string | null;
};

export type BlogCategories = Models.Document & {
  name: string;
  slug: string;
};

export type BlogPosts = Models.Document & {
  category_id: string | null;
  title: string;
  slug: string;
  content: string;
  is_published: boolean;
};

export type Notifications = Models.Document & {
  user_id: string;
  title: string;
  message: string;
  type: Type;
  is_read: boolean;
};

export type Promocodes = Models.Document & {
  code: string;
  discount_type: DiscountType;
  discount_value: number;
  is_active: boolean;
  valid_from: string;
  valid_until: string;
};

export type ContactInquiries = Models.Document & {
  name: string;
  email: string;
  subject: string;
  message: string;
  status: Status;
};

export type ServicePackages = Models.Document & {
  name: string;
  price: number;
  currency: string;
  duration: string | null;
  ideal: string | null;
  features: string[] | null;
  popular: boolean;
  service_id: string;
  description: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string | null;
  updated_at: string | null;
};
